spring.application.name=gtime
spring.datasource.url=jdbc:postgresql://localhost:5432/gtime
spring.datasource.username=postgres
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

jwt.secret=f4a5e00d57b879a75131df8dd1cff23e2599ae63f3b9ae22620d248263c057ca
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000