type Detail {
    id: ID!
    name: String!
    text: String!
}

input DetailInput {
    name: String!
    text: String!
}

input EditDetailInput {
    name: String
    text: String
}

extend type Mutation {
    # Admin
    createDetail(input: DetailInput!): Detail!
    # Admin
    editDetail(detailId: ID!, detail: EditDetailInput!): Detail!
    # Admin
    deleteDetail(detailId: ID!): Boolean!
}

extend type Query {
    # Anyone
    details: [Detail!]!
    # Anyone
    detail(id: ID!): Detail!
}
