type Plant {
    id: ID!
    name: String!
    latinName: String!
    description: String!
    image: String!
    details: [Detail!]!
    careDifficulty: CareDifficulty!
    wateringFrequency: WateringFrequency!
}

enum TimeUnit {
    NANOSECONDS
    MICROSECONDS
    MILLISECONDS
    SECONDS
    MINUTES
    HOURS
    DAYS
}

input WateringFrequencyInput {
    length: ID!
    timeUnit: TimeUnit!
    plantStage: PlantGrowthStageInput!
}

input PlantGrowthStageInput {
    name: String!
}

type PlantGrowthStage {
    name: String!
}

type WateringFrequency {
    length: ID!
    timeUnit: TimeUnit!
}

input PlantInput {
    name: String!
    latinName: String!
    description: String!
    image: String!
    details: [ID!]!
    careDifficulty: CareDifficulty!
    wateringFrequencies: [WateringFrequencyInput!]!
}

input EditPlantInput {
    name: String
    details: [ID!]
}

enum CareDifficulty {
    EASY,
    NORMAL,
    HARD
}

extend type Mutation {
    # Admin only
    createPlant(input: PlantInput!): Plant!
    # Admin only
    editPlant(plantId: ID!, plantDetails: EditPlantInput!): Plant!
    # Admin only
    deletePlant(plantId: ID!): Boolean!
}

extend type Query {
    # Anyone
    plants: [Plant!]!
    # Anyone
    plant(id: ID!): Plant
}