extend type Query {
    myPlants: [UserPlant!]
}

extend type Mutation {
    createUserPlant(userPlantInput: UserPlantInput!): UserPlant!
}

input UserPlantInput {
    plantType: ID!
    name: String!
}

input EditUserPlantInput {
    name: String!

}

type UserPlant {
    plantType: UserPlantType!
    name: String!
    growthStage: PlantGrowthStage!
}

type UserPlantType {
    id: ID!
    name: String!
    latinName: String!
    description: String!
    image: String!
    details: [Detail!]!
    careDifficulty: CareDifficulty!
    growthStage: PlantGrowthStage!
    wateringFrequency: WateringFrequency!
}